default_language_version:
  python: python3.10

fail_fast: true

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          ["--ignore=E402, E501, W503"]
          # E402 = module level import not at top of file
          # E501 = line too long
          # W503 = line break occurred before a binary operator
          # E712 = comparison to False should be 'if cond is False:' or 'if not cond:'
          # E713 = test for membership should be 'not in'
          # E722 = do not use bare 'except'

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--expand-star-imports",
            "--remove-duplicate-keys",
            "--remove-unused-variables",
          ]
