from enum import Enum


class MapID(Enum):
    EDEL_VALE = 0
    OVERWORLD = 1
    MEADOW = 2
    PAPURIKA = 3
    PAPURIKA_WELL = 4
    NORIA_CLOSED = 5
    NORIA = 6
    CRYSTAL_CAVERN = 7
    PAPURIKA_INTERIOR = 8
    HIDDEN_MEADOW = 9
    HIDDEN_MEADON_CAVE = 10
    LIMBO = 11
    AOGAI = 12
    SACRED_GROVE_2D = 13
    SACRED_GROVE_3D = 14
    SARUDNAHK = 15
    SACRED_GROVE_CAVE_1 = 16
    SACRED_GROVE_CAVE_2 = 17
    BABAMUT_SHRINE = 18
    FORBIDDEN_LAKE_2D = 19
    FORBIDDEN_LAKE_3D = 20
    END = 21
